"""empty message

Revision ID: 8399aad619e7
Revises: ffdc0a98111c
Create Date: 2023-07-23 19:31:05.097238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8399aad619e7'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('preview',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('recipe_type',
               existing_type=sa.VARCHAR(length=9),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('recipe_type',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.alter_column('preview',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###